services:
  - type: web
    name: shruti-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 -m ShrutiMusic
    autoDeploy: true

    envVars:
      API_ID: 
        value: 29448785
      API_HASH: 
        value: 599574f6aff0a09ebb76305b58e7e9c2
      API_KEY:
        sync: false
      BOT_TOKEN:
        sync: false
      MONGO_DB_URI: 
        value: mongodb+srv://pusers:nycreation@nycreation.pd4klp1.mongodb.net/?retryWrites=true&w=majority&appName=NYCREATION
      OWNER_ID:
        value: 8042205941
      OWNER_USERNAME:
        value: SlayWithRose
      BOT_USERNAME:
        value: BillieMusicBot
      UPSTREAM_REPO:
        value: https://t.me/FakeAaru
      STRING_SESSION:
        sync: false
      GIT_TOKEN:
        sync: false
      HEROKU_API_KEY:
        sync: false
      HEROKU_APP_NAME:
        sync: false
      LOG_GROUP_ID:
        value: -1002321189618
      SUPPORT_GROUP:
        value: https://t.me/FakeAaru
      SUPPORT_CHANNEL:
        value: https://t.me/FakeAaru
      INSTAGRAM:
        value: https://t.me/FakeAaru
      YOUTUBE:
        value: https://t.me/FakeAaru
      GITHUB:
        value: https://t.me/FakeAaru
      DONATE:
        value: https://t.me/FakeAaru
      START_IMG_URL:
        sync: false
